(()=>{
  'use strict';
  const DASH_API='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/admin-dashboard-api';
  const CONTROL_API='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/admin-control-center';
  const TRASH_API='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/admin-trash-api';
  let ccContext=null,ccDashboard=null,ccPrefs={widgets:[],layout:{}};
  const PERMISSIONS=[
    ['dashboard.read','Tableau de bord'],['activity.read','Historique global'],['analytics.read','Statistiques'],['suppliers.read','Fournisseurs'],['search.read','Recherche globale'],['apps.read','Santé des applications'],['audit.read','Journal d’audit'],['trash.read','Voir la corbeille'],['trash.manage','Restaurer / gérer la corbeille'],['accounting.read','Contrôle comptabilité'],['secretariat.read','Contrôle secrétariat'],['anomalies.read','Voir les anomalies'],['anomalies.manage','Acquitter les anomalies'],['export.read','Exports'],['products.read','Produits'],['stock.read','Stocks'],['purchases.read','Achats']
  ];
  const EXTRA_PAGES=[
    ['activityCenter','Activité globale','activity.read'],['analyticsCenter','Analyse & périodes','analytics.read'],['suppliersCenter','Fournisseurs','suppliers.read'],['globalSearch','Recherche globale','search.read'],['appHealth','Santé applications','apps.read'],['auditCenter','Journal d’audit','audit.read'],['trashCenter','Corbeille','trash.read'],['accountingCenter','Centre comptabilité','accounting.read'],['secretariatCenter','Centre secrétariat','secretariat.read'],['anomaliesCenter','Anomalies','anomalies.read'],['directionCenter','Vue direction','dashboard.read'],['dashboardPrefs','Personnaliser','dashboard.read'],['adminAccounts','Comptes administrateurs','__super__']
  ];
  EXTRA_PAGES.forEach(([k,n])=>{if(!pages.some(x=>x[0]===k))pages.splice(Math.max(1,pages.length-1),0,[k,n])});
  const style=document.createElement('style');style.textContent=`
  .cc-red{border:1px solid #e0a0a0!important;background:#fff2f2!important;color:#7f1616}.cc-red strong,.cc-red b{color:#8f1111}.cc-warn{border:1px solid #e4c682!important;background:#fff9e8!important}.cc-ok{border:1px solid #b9d8c3!important;background:#f2fbf5!important}.cc-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.cc-alert-row{padding:12px;border-radius:10px;margin:8px 0}.cc-search-results{display:grid;gap:8px}.cc-search-item{padding:12px;border:1px solid #dde3e8;border-radius:10px;background:#fff}.cc-perms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cc-perm{display:flex;gap:8px;align-items:center;border:1px solid #dde3e8;border-radius:9px;padding:9px;background:#f9fafb}.cc-perm input{width:auto}.cc-health-ok{color:#176b3a;font-weight:800}.cc-health-bad{color:#a32929;font-weight:800}.cc-filterbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.cc-filterbar input,.cc-filterbar select{width:auto;min-width:180px}@media(max-width:900px){.cc-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.cc-kpis,.cc-perms{grid-template-columns:1fr}}
  `;document.head.appendChild(style);
  async function req(base,action='context',method='GET',body,params={}){const u=new URL(base);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{method,headers:{'content-type':'application/json',authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Réponse invalide'}));if(r.status===401){logout();throw new Error('Session expirée')}if(!r.ok)throw new Error(j.error||'Erreur serveur');return j}
  const dash=(a,m='GET',b,p)=>req(DASH_API,a,m,b,p),control=(a,m='GET',b)=>req(CONTROL_API,a,m,b),trash=(a,m='GET',b)=>req(TRASH_API,a,m,b);
  function can(p){if(!ccContext)return false;return !!ccContext.current_user?.is_super_admin||ccContext.current_user?.permissions?.['*']===true||ccContext.current_user?.permissions?.[p]===true}
  function isSuper(){return !!ccContext?.current_user?.is_super_admin}
  function pagePermission(k){const x=EXTRA_PAGES.find(p=>p[0]===k);if(x)return x[2];if(['dashboard','settings'].includes(k))return 'dashboard.read';if(['products'].includes(k))return 'products.read';if(['purchases'].includes(k))return 'purchases.read';if(['events','stats'].includes(k))return 'analytics.read';if(['apps','categories'].includes(k))return 'apps.read';if(['accountingRules','accountingControl','windowsAgent'].includes(k))return 'accounting.read';return null}
  const baseInitNav=initNav;
  initNav=function(){const visible=pages.filter(([k])=>{const p=pagePermission(k);return !p||(p==='__super__'?isSuper():can(p))});$('nav').innerHTML=visible.map(([k,n])=>`<button data-p="${k}" onclick="show('${k}')">${n}</button>`).join('')};
  const baseRefresh=refresh;
  refresh=async function(){try{ccContext=await dash('context');const main=await api('data');let sites={applications:main.applications||[],application_products:main.application_products||[]};if(can('apps.read')){try{sites=await siteApi('list')}catch{}}db=main;db.applications=sites.applications||[];db.application_products=sites.application_products||[];if(can('dashboard.read')){try{ccDashboard=await dash('dashboard');ccPrefs=await dash('preferences')}catch{ccDashboard=null}}$('serverTime').textContent='Données actualisées : '+new Date(db.server_time||Date.now()).toLocaleString('fr-FR')+' · '+esc(ccContext.current_user?.display_name||ccContext.current_user?.username||'');initNav();render()}catch(e){alert(e.message)}};
  const baseRender=render;
  render=function(){if(!db)return;const extra={activityCenter:renderActivityCenter,analyticsCenter:renderAnalyticsCenter,suppliersCenter:renderSuppliersCenter,globalSearch:renderGlobalSearch,appHealth:renderAppHealth,auditCenter:renderAuditCenter,trashCenter:renderTrashCenter,accountingCenter:renderAccountingCenter,secretariatCenter:renderSecretariatCenter,anomaliesCenter:renderAnomaliesCenter,directionCenter:renderDirectionCenter,dashboardPrefs:renderDashboardPrefs,adminAccounts:renderAdminAccounts};if(extra[page]){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===page));$('pageTitle').textContent=pages.find(x=>x[0]===page)?.[1]||'';extra[page]();return}baseRender()};
  function money(v){return Number(v||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
  function pct(a,b){return b?((a/b)*100).toFixed(1)+' %':'—'}
  function widgetOn(k){return !Array.isArray(ccPrefs.widgets)||!ccPrefs.widgets.length||ccPrefs.widgets.includes(k)}
  renderDashboard=function(){if(!ccDashboard){$('content').innerHTML='<div class="card"><div class="muted">Tableau de bord indisponible pour ce compte.</div></div>';return}const k=ccDashboard.kpis||{},critical=Number(k.accounting_to_control||0)+Number(k.negative_stock||0);$('content').innerHTML=`${widgetOn('alerts')&&critical?`<div class="card cc-red"><h3>À CONTRÔLER</h3><div><b>${critical}</b> contrôle(s) prioritaire(s) détecté(s). <button class="btn danger" onclick="show('anomaliesCenter')">Voir exactement pourquoi</button></div></div><br>`:''}<div class="cc-kpis">${widgetOn('stock')?`<div class="card"><div class="muted">Valeur du stock</div><div class="kpi">${money(k.stock_value)}</div><div class="muted">${k.low_stock||0} sous seuil · ${k.negative_stock||0} négatif</div></div>`:''}${widgetOn('purchases')?`<div class="card"><div class="muted">Achats du mois</div><div class="kpi">${money(k.purchases_month)}</div><div class="muted">Prévision fin de mois : ${money(k.forecast_month)}</div></div>`:''}${widgetOn('accounting')?`<div class="card ${k.accounting_to_control?'cc-red':''}"><div class="muted">Comptabilité à contrôler</div><div class="kpi">${k.accounting_to_control||0}</div><div class="muted">${k.accounting_validated||0} validée(s)</div></div>`:''}${widgetOn('apps')?`<div class="card"><div class="muted">Applications actives</div><div class="kpi">${k.applications_active||0}</div><div class="muted">${k.products||0} produits actifs</div></div>`:''}</div><br><div class="grid"><div class="card"><h3>Pilotage</h3><p><button class="btn secondary" onclick="show('activityCenter')">Historique global</button> <button class="btn secondary" onclick="show('analyticsCenter')">Statistiques</button></p></div><div class="card"><h3>Contrôles</h3><p><button class="btn danger" onclick="show('anomaliesCenter')">Anomalies</button> <button class="btn secondary" onclick="show('appHealth')">Santé des apps</button></p></div><div class="card"><h3>Finance</h3><p><button class="btn secondary" onclick="show('suppliersCenter')">Fournisseurs</button> <button class="btn secondary" onclick="show('accountingCenter')">Comptabilité</button></p></div><div class="card"><h3>Direction</h3><p><button class="btn primary" onclick="show('directionCenter')">Vue synthétique</button></p></div></div>`};
  async function renderActivityCenter(){try{const j=await dash('activity');$('content').innerHTML=`<div class="cc-filterbar"><input id="ccActSearch" placeholder="Utilisateur, action, élément" oninput="filterCcActivity()"></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Utilisateur</th><th>Action</th><th>Élément</th><th>Détails</th></tr></thead><tbody id="ccActBody">${(j.rows||[]).map(r=>`<tr data-s="${esc([r.username,r.action,r.entity_type,r.entity_id,JSON.stringify(r.details||{})].join(' ').toLowerCase())}"><td>${new Date(r.created_at).toLocaleString('fr-FR')}</td><td>${esc(r.username)}</td><td><b>${esc(r.action)}</b></td><td>${esc(r.entity_type||'')} ${esc(r.entity_id||'')}</td><td><span class="muted">${esc(JSON.stringify(r.details||{}))}</span></td></tr>`).join('')}</tbody></table></div>`}catch(e){showErr(e)}}
  window.filterCcActivity=function(){const q=String($('ccActSearch')?.value||'').toLowerCase();document.querySelectorAll('#ccActBody tr').forEach(tr=>tr.style.display=!q||String(tr.dataset.s||'').includes(q)?'':'none')};
  async function renderAnalyticsCenter(days=30){try{const j=await dash('analytics','GET',null,{days});const c=j.category_consumption||[],buy=(j.purchases||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_price||0),0);$('content').innerHTML=`<div class="toolbar"><button class="btn ${days===7?'primary':'secondary'}" onclick="renderAnalyticsCenter(7)">7 jours</button><button class="btn ${days===30?'primary':'secondary'}" onclick="renderAnalyticsCenter(30)">30 jours</button><button class="btn ${days===90?'primary':'secondary'}" onclick="renderAnalyticsCenter(90)">90 jours</button><button class="btn ${days===365?'primary':'secondary'}" onclick="renderAnalyticsCenter(365)">1 an</button></div><div class="cc-kpis"><div class="card"><div class="muted">Achats période</div><div class="kpi">${money(buy)}</div></div><div class="card"><div class="muted">Opérations stock</div><div class="kpi">${(j.events||[]).length}</div></div></div><br><div class="table-wrap"><table><thead><tr><th>Catégorie</th><th>Sorties</th><th>Valeur sorties</th><th>Achats</th><th>Valeur achats</th></tr></thead><tbody>${c.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${Number(x.outgoing||0).toLocaleString('fr-FR')}</td><td>${money(x.outgoing_value)}</td><td>${Number(x.purchases||0).toLocaleString('fr-FR')}</td><td>${money(x.purchase_value)}</td></tr>`).join('')}</tbody></table></div>`}catch(e){showErr(e)}}window.renderAnalyticsCenter=renderAnalyticsCenter;
  async function renderSuppliersCenter(){try{const j=await dash('suppliers');$('content').innerHTML=`<div class="cc-filterbar"><input id="ccSupSearch" placeholder="Rechercher un fournisseur" oninput="filterCcSuppliers()"></div><div class="table-wrap"><table><thead><tr><th>Fournisseur</th><th>Achats</th><th>Montant total</th><th>Produits</th><th>Dernier achat</th></tr></thead><tbody id="ccSupBody">${(j.suppliers||[]).map(x=>`<tr data-s="${esc(String(x.supplier).toLowerCase())}"><td><b>${esc(x.supplier)}</b></td><td>${x.purchases}</td><td>${money(x.amount)}</td><td>${x.products}</td><td>${esc(x.last_purchase||'—')}</td></tr>`).join('')}</tbody></table></div>`}catch(e){showErr(e)}}window.filterCcSuppliers=function(){const q=String($('ccSupSearch')?.value||'').toLowerCase();document.querySelectorAll('#ccSupBody tr').forEach(tr=>tr.style.display=!q||String(tr.dataset.s||'').includes(q)?'':'none')};
  function renderGlobalSearch(){$('content').innerHTML=`<div class="card"><h3>Recherche générale</h3><div class="row"><input id="ccSearch" placeholder="Produit, référence, fournisseur, facture, application…" onkeydown="if(event.key==='Enter')ccRunSearch()"><button class="btn primary" onclick="ccRunSearch()">Rechercher</button></div></div><br><div id="ccSearchResults"></div>`}window.ccRunSearch=async function(){const q=$('ccSearch').value.trim(),box=$('ccSearchResults');if(q.length<2){box.innerHTML='<div class="muted">Saisir au moins 2 caractères.</div>';return}box.innerHTML='<div class="muted">Recherche…</div>';try{const j=await dash('search','GET',null,{q});box.innerHTML=`<div class="cc-search-results">${(j.results||[]).map(x=>`<div class="cc-search-item"><div class="pill">${esc(x.type)}</div><h3 style="margin-top:7px">${esc(x.title)}</h3><div class="muted">${esc(x.subtitle||'')}</div></div>`).join('')||'<div class="card">Aucun résultat.</div>'}</div>`}catch(e){box.innerHTML=`<div class="err">${esc(e.message)}</div>`}};
  async function renderAppHealth(){try{const j=await dash('apps');$('content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Application</th><th>État</th><th>Produits</th><th>Dernière activité</th><th>Contrôle</th></tr></thead><tbody>${(j.applications||[]).map(a=>`<tr class="${a.health==='ok'?'':'cc-red'}"><td><b>${esc(a.name)}</b><div class="muted">${esc(a.code)}</div></td><td class="${a.health==='ok'?'cc-health-ok':'cc-health-bad'}">${a.health==='ok'?'OK':'À CONTRÔLER'}</td><td>${a.product_count}</td><td>${a.last_activity_at?new Date(a.last_activity_at).toLocaleString('fr-FR'):'Aucune activité enregistrée'}</td><td>${a.issues?.length?esc(a.issues.join(' ; ')):'Aucune anomalie de configuration détectée'}</td></tr>`).join('')}</tbody></table></div>`}catch(e){showErr(e)}}
  async function renderAuditCenter(){return renderActivityCenter()}
  async function renderTrashCenter(){try{const j=await trash('list');$('content').innerHTML=`<div class="card"><div class="muted">Les éléments supprimés sont conservés 30 jours avant purge automatique.</div></div><br><div class="table-wrap"><table><thead><tr><th>Élément</th><th>Supprimé par</th><th>Date</th><th>Purge prévue</th><th></th></tr></thead><tbody>${(j.rows||[]).map(x=>`<tr><td><b>${esc(x.entity_type)}</b><div class="muted">${esc(x.entity_data?.name||x.entity_data?.code||x.entity_id)}</div></td><td>${esc(x.deleted_by)}</td><td>${new Date(x.deleted_at).toLocaleString('fr-FR')}</td><td>${new Date(x.purge_after).toLocaleString('fr-FR')}</td><td>${can('trash.manage')?`<button class="btn primary" onclick="ccRestoreTrash('${x.id}')">Restaurer</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Corbeille vide.</td></tr>'}</tbody></table></div>`}catch(e){showErr(e)}}window.ccRestoreTrash=async function(id){if(!confirm('Restaurer cet élément ?'))return;try{await trash('restore','POST',{id});await renderTrashCenter();await refresh()}catch(e){alert(e.message)}};
  function accountingReasons(i){const r=[];if(!i.supplier)r.push('fournisseur non identifié');if(!i.invoice_number)r.push('numéro manquant');if(!i.invoice_date)r.push('date manquante');if(i.amount_ht==null||i.amount_vat==null||i.amount_ttc==null)r.push('montants incomplets');else if(Math.abs(Number(i.amount_ht)+Number(i.amount_vat)-Number(i.amount_ttc))>.02)r.push('HT + TVA ≠ TTC');if(Array.isArray(i.warnings)&&i.warnings.length)r.push('avertissements de lecture');if(['a_controler','erreur'].includes(String(i.status)))r.push('statut '+i.status);return r}
  async function renderAccountingCenter(){try{const j=await dash('accounting'),rows=j.invoices||[],bad=rows.filter(x=>accountingReasons(x).length);$('content').innerHTML=`<div class="cc-kpis"><div class="card cc-red"><div class="muted">À contrôler</div><div class="kpi">${bad.length}</div></div><div class="card"><div class="muted">Validées</div><div class="kpi">${rows.filter(x=>x.status==='validee').length}</div></div></div><br><div class="table-wrap"><table><thead><tr><th>Facture</th><th>Date</th><th>TTC</th><th>Statut</th><th>Contrôle exact</th></tr></thead><tbody>${rows.map(i=>{const r=accountingReasons(i);return `<tr class="${r.length?'cc-red':''}"><td><b>${esc(i.supplier||'Fournisseur inconnu')}</b><div class="muted">${esc(i.invoice_number||'sans numéro')}</div></td><td>${esc(i.invoice_date||'—')}</td><td>${money(i.amount_ttc)}</td><td>${esc(i.status)}</td><td>${r.length?'<b>À CONTRÔLER :</b> '+esc(r.join(' ; ')):'OK'}</td></tr>`}).join('')}</tbody></table></div>`}catch(e){showErr(e)}}
  function secLineReasons(l){const r=[];if(!l.product_id)r.push('produit non rapproché');if(l.double_read_agreement===false)r.push('désaccord double lecture');if(l.reader_confidence!=null&&Number(l.reader_confidence)<.98)r.push('confiance '+(Number(l.reader_confidence)*100).toFixed(1)+' %');const q=Number(l.invoice_quantity||l.quantity||0),pu=Number(l.unit_price_ttc||l.unit_price_ht||0),tot=Number(l.line_total_ttc||l.line_total_ht||0);if(q>0&&pu>0&&tot>0&&Math.abs(q*pu-tot)>.05)r.push('quantité × prix ≠ total ligne');return r}
  async function renderSecretariatCenter(){try{const j=await dash('secretariat'),items=j.items||[],bad=items.filter(x=>secLineReasons(x).length);$('content').innerHTML=`<div class="cc-kpis"><div class="card"><div class="muted">Lignes lues</div><div class="kpi">${j.total_lines||0}</div></div><div class="card ${(j.matched_lines||0)<(j.total_lines||0)?'cc-red':''}"><div class="muted">Produits rapprochés</div><div class="kpi">${pct(j.matched_lines,j.total_lines)}</div></div><div class="card ${(j.double_read_ok||0)<(j.total_lines||0)?'cc-red':''}"><div class="muted">Double lecture conforme</div><div class="kpi">${pct(j.double_read_ok,j.total_lines)}</div></div><div class="card ${bad.length?'cc-red':''}"><div class="muted">Lignes à contrôler</div><div class="kpi">${bad.length}</div></div></div><br><div class="table-wrap"><table><thead><tr><th>Produit détecté</th><th>Référence</th><th>Quantité</th><th>Confiance</th><th>Contrôle exact</th></tr></thead><tbody>${items.map(l=>{const r=secLineReasons(l);return `<tr class="${r.length?'cc-red':''}"><td>${esc(l.detected_label||'—')}</td><td>${esc(l.detected_reference||'—')}</td><td>${Number(l.invoice_quantity||l.quantity||0)}</td><td>${l.reader_confidence==null?'—':(Number(l.reader_confidence)*100).toFixed(1)+' %'}</td><td>${r.length?'<b>À CONTRÔLER :</b> '+esc(r.join(' ; ')):'OK'}</td></tr>`}).join('')}</tbody></table></div>`}catch(e){showErr(e)}}
  async function renderAnomaliesCenter(){try{const j=await dash('anomalies');const rows=j.rows||[];$('content').innerHTML=`<div class="cc-kpis"><div class="card cc-red"><div class="muted">Critiques</div><div class="kpi">${rows.filter(x=>x.severity==='critical').length}</div></div><div class="card cc-warn"><div class="muted">Avertissements</div><div class="kpi">${rows.filter(x=>x.severity==='warning').length}</div></div></div><br>${rows.map(x=>`<div class="cc-alert-row ${x.severity==='critical'?'cc-red':'cc-warn'}"><div><b>${x.severity==='critical'?'À CONTRÔLER IMMÉDIATEMENT':'À CONTRÔLER'}</b> · ${esc(x.domain)}</div><h3>${esc(x.title)}</h3><div>${esc(x.reason)}</div>${can('anomalies.manage')?`<div style="margin-top:8px"><button class="btn secondary" onclick="ccAckAnomaly('${esc(x.key)}')">Marquer comme vu</button></div>`:''}</div>`).join('')||'<div class="card cc-ok"><b>Aucune anomalie détectée par les contrôles actifs.</b></div>'}`}catch(e){showErr(e)}}window.ccAckAnomaly=async function(key){try{await dash('ack-anomaly','POST',{key});await renderAnomaliesCenter()}catch(e){alert(e.message)}};
  function renderDirectionCenter(){if(!ccDashboard)return showErr(new Error('Données indisponibles'));const k=ccDashboard.kpis||{},risk=Number(k.accounting_to_control||0)+Number(k.negative_stock||0);$('content').innerHTML=`<div class="cc-kpis"><div class="card"><div class="muted">Dépenses du mois</div><div class="kpi">${money(k.purchases_month)}</div></div><div class="card"><div class="muted">Prévision fin de mois</div><div class="kpi">${money(k.forecast_month)}</div></div><div class="card"><div class="muted">Valeur stock</div><div class="kpi">${money(k.stock_value)}</div></div><div class="card ${risk?'cc-red':'cc-ok'}"><div class="muted">Contrôles prioritaires</div><div class="kpi">${risk}</div></div></div><br><div class="grid"><div class="card"><h3>Stock</h3><div>${k.low_stock||0} produit(s) sous seuil</div><div>${k.negative_stock||0} stock(s) négatif(s)</div></div><div class="card"><h3>Comptabilité</h3><div>${k.accounting_to_control||0} facture(s) à contrôler</div><div>${k.accounting_validated||0} validée(s)</div></div><div class="card"><h3>Applications</h3><div>${k.applications_active||0} actives</div></div><div class="card"><h3>Achats annuels</h3><div class="kpi" style="font-size:22px">${money(k.purchases_year)}</div></div></div>`}
  function renderDashboardPrefs(){const all=[['stock','Valeur du stock'],['purchases','Achats et prévision'],['accounting','Contrôle comptabilité'],['apps','Applications'],['alerts','Bloc alertes rouges']],selected=new Set(ccPrefs.widgets||[]);$('content').innerHTML=`<div class="card" style="max-width:700px"><h3>Personnalisation du tableau de bord</h3><div class="muted">Si aucune option n’est cochée, tous les blocs sont affichés.</div><div class="cc-perms" style="margin-top:12px">${all.map(([k,n])=>`<label class="cc-perm"><input class="cc-widget" type="checkbox" value="${k}" ${selected.has(k)?'checked':''}> ${n}</label>`).join('')}</div><br><button class="btn primary" onclick="ccSavePrefs()">Enregistrer</button></div>`}window.ccSavePrefs=async function(){const widgets=[...document.querySelectorAll('.cc-widget:checked')].map(x=>x.value);try{await dash('preferences','POST',{widgets,layout:{}});ccPrefs={widgets,layout:{}};alert('Tableau de bord personnalisé.')}catch(e){alert(e.message)}};
  async function renderAdminAccounts(){if(!isSuper())return showErr(new Error('Réservé à l’administrateur principal'));try{const j=await control('accounts');$('content').innerHTML=`<div class="toolbar"><button class="btn primary" onclick="ccEditAdmin()">+ Ajouter un administrateur</button></div><div class="card"><b>Administrateur principal :</b> ${esc(ccContext.current_user.username)}. Lui seul peut créer, désactiver et configurer les autres comptes.</div><br><div class="table-wrap"><table><thead><tr><th>Compte</th><th>Rôle</th><th>État</th><th>Dernière connexion</th><th>Droits</th><th></th></tr></thead><tbody>${(j.accounts||[]).map(a=>`<tr><td><b>${esc(a.display_name||a.username)}</b><div class="muted">${esc(a.username)}</div></td><td>${a.is_super_admin?'<span class="pill">Principal</span>':'Administrateur limité'}</td><td>${a.active?'Actif':'Désactivé'}</td><td>${a.last_login_at?new Date(a.last_login_at).toLocaleString('fr-FR'):'Jamais'}</td><td>${a.is_super_admin?'Tous':esc(Object.keys(a.permissions||{}).filter(k=>a.permissions[k]===true).join(', ')||'Aucun')}</td><td>${a.is_super_admin?'':`<button class="btn secondary" onclick="ccEditAdmin('${esc(a.username)}')">Configurer</button>`}</td></tr>`).join('')}</tbody></table></div>`;window._ccAccounts=j.accounts||[]}catch(e){showErr(e)}}
  window.ccEditAdmin=function(username=''){const a=(window._ccAccounts||[]).find(x=>x.username===username)||{},perms=a.permissions||{};$('modal').innerHTML=`<div class="modal"><div class="box"><h2>${username?'Configurer le compte':'Nouvel administrateur'}</h2><div class="fields"><div><label>Identifiant</label><input id="ccaUser" value="${esc(a.username||'')}" ${username?'disabled':''}></div><div><label>Nom affiché</label><input id="ccaName" value="${esc(a.display_name||'')}"></div><div class="full"><label>${username?'Nouveau mot de passe (laisser vide pour conserver)':'Mot de passe initial (14 caractères minimum)'}</label><input id="ccaPass" type="password" autocomplete="new-password"></div><div class="full"><label><input id="ccaActive" type="checkbox" style="width:auto" ${a.active!==false?'checked':''}> Compte actif</label></div></div><div class="section-title">Permissions</div><div class="cc-perms">${PERMISSIONS.map(([k,n])=>`<label class="cc-perm"><input class="ccaPerm" type="checkbox" value="${k}" ${perms[k]===true?'checked':''}> ${esc(n)}</label>`).join('')}</div><div class="actions" style="margin-top:16px"><button class="btn primary" onclick="ccSaveAdmin('${esc(username)}')">Enregistrer</button><button class="btn secondary" onclick="closeModal()">Annuler</button></div><div id="ccaStatus" class="status"></div></div></div>`};
  window.ccSaveAdmin=async function(existing=''){const permissions={};document.querySelectorAll('.ccaPerm:checked').forEach(x=>permissions[x.value]=true);permissions['dashboard.read']=true;const body={username:existing||$('ccaUser').value.trim(),display_name:$('ccaName').value.trim(),password:$('ccaPass').value,active:$('ccaActive').checked,permissions};const s=$('ccaStatus');try{s.textContent='Enregistrement sécurisé…';await control('save-account','POST',body);closeModal();await renderAdminAccounts()}catch(e){s.className='status err';s.textContent=e.message}};
  const oldDeleteProduct=window.deleteProduct,oldDeleteSite=window.deleteSite;
  if(oldDeleteProduct)window.deleteProduct=async function(id){try{if(can('trash.manage')||isSuper())await trash('snapshot','POST',{entity_type:'product',entity_id:id})}catch(e){if(!confirm('La sauvegarde en corbeille a échoué. Continuer la suppression ?'))return}return oldDeleteProduct(id)};
  if(oldDeleteSite)window.deleteSite=async function(id){try{if(can('trash.manage')||isSuper())await trash('snapshot','POST',{entity_type:'application',entity_id:id})}catch(e){if(!confirm('La sauvegarde en corbeille a échoué. Continuer la suppression ?'))return}return oldDeleteSite(id)};
  const oldExport=exportExcel;
  exportExcel=async function(){if(!can('export.read')&&!isSuper())return alert('Permission export requise.');try{if(typeof XLSX==='undefined')return oldExport();const wb=XLSX.utils.book_new();const add=(n,d)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d||[]),n);add('Stocks',db.products.filter(p=>p.active).map(p=>({Code:p.code,Produit:p.name,Catégorie:catById(p.category_id)?.name||'',Stock:bal(p.id),Prix:Number(p.unit_price||0),Valeur:bal(p.id)*Number(p.unit_price||0)})));if(can('analytics.read')){const a=await dash('analytics','GET',null,{days:365});add('Consommation_categories',a.category_consumption||[]);add('Achats_365j',a.purchases||[])}if(can('suppliers.read')){const s=await dash('suppliers');add('Fournisseurs',s.suppliers||[])}if(can('anomalies.read')){const x=await dash('anomalies');add('Anomalies',x.rows||[])}if(can('activity.read')||can('audit.read')){const x=await dash('activity');add('Audit',x.rows||[])}XLSX.writeFile(wb,'Gestion_College_Admin_'+new Date().toISOString().slice(0,10)+'.xlsx')}catch(e){alert(e.message)}};
  function showErr(e){$('content').innerHTML=`<div class="card cc-red"><b>Erreur</b><div>${esc(e.message||String(e))}</div></div>`}
  if(token){setTimeout(()=>refresh().catch(()=>{}),80)}
})();