const SANDBOX_API='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/sandbox-api';
let sandboxData=null;
async function sandboxApi(action='overview',method='GET',body){const r=await fetch(SANDBOX_API+'?action='+encodeURIComponent(action),{method,headers:{'content-type':'application/json',authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Réponse invalide'}));if(r.status===401||r.status===403)throw new Error(j.error||'Accès refusé');if(!r.ok)throw new Error(j.error||'Erreur serveur');return j}
if(!pages.some(x=>x[0]==='sandbox'))pages.splice(Math.max(0,pages.length-1),0,['sandbox','Bac à sable']);
const sandboxBaseRender=render;
render=function(){if(page==='sandbox'){if(!db)return;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===page));$('pageTitle').textContent='Bac à sable';return renderSandbox()}return sandboxBaseRender()};
const sandboxBaseInitNav=initNav;
initNav=function(){sandboxBaseInitNav()};
if(token&&$('nav'))initNav();
function sbMoney(v){return Number(v||0).toFixed(2).replace('.',',')+' €'}
function sbBadge(s){const map={brouillon:'Brouillon',commandee:'Commandée',recue:'Reçue',annulee:'Annulée',a_controler:'À contrôler',validee:'Validée',exportee:'OD générée',importee:'Importée Charlemagne',erreur:'Erreur',generated:'À confirmer',imported:'Importé',cancelled:'Annulé'};return `<span class="pill">${esc(map[s]||s)}</span>`}
async function renderSandbox(){const c=$('content');c.innerHTML='<div class="card"><h3>Bac à sable</h3><div class="muted">Chargement…</div></div>';try{sandboxData=await sandboxApi('overview');drawSandbox()}catch(e){c.innerHTML=`<div class="card"><h3>Bac à sable</h3><div class="err">${esc(e.message)}</div></div>`}}
function drawSandbox(){const d=sandboxData||{},test=!!d.test_mode,products=d.products||[],orders=d.orders||[],invoices=d.invoices||[],batches=d.batches||[],low=products.filter(p=>p.active&&Number(p.stock)<=Number(p.min_stock)).length;$('content').innerHTML=`
<div class="card" style="border:2px solid ${test?'#8a1c1c':'#c7d0d9'}"><div class="actions" style="justify-content:space-between;align-items:flex-start"><div><h2>BAC À SABLE</h2><div class="muted">Données 100 % fictives, stockées dans des tables sandbox_* séparées de la production.</div></div><span class="pill">${test?'MODE TEST ACTIF':'MODE TEST REQUIS'}</span></div>${test?'<p class="ok"><b>Production protégée.</b> Les opérations ci-dessous modifient uniquement le bac à sable.</p>':'<p class="alert"><b>Active le Mode test global dans Paramètres avant d’utiliser le bac à sable.</b></p>'}<div class="actions"><button class="btn primary" onclick="sandboxSeed()" ${test?'':'disabled'}>Charger un jeu de données test</button><button class="btn danger" onclick="sandboxReset()" ${test?'':'disabled'}>Remettre le bac à sable à zéro</button><button class="btn secondary" onclick="renderSandbox()">Actualiser</button></div></div>
<br><div class="grid"><div class="card"><div class="muted">Produits test</div><div class="kpi">${products.length}</div></div><div class="card"><div class="muted">Sous minimum</div><div class="kpi">${low}</div></div><div class="card"><div class="muted">Commandes test</div><div class="kpi">${orders.length}</div></div><div class="card"><div class="muted">Factures test</div><div class="kpi">${invoices.length}</div></div></div>
<br><div class="card"><div class="actions" style="justify-content:space-between"><div><h3>Stocks test</h3><div class="muted">Aucun stock réel n’est utilisé.</div></div><button class="btn primary" onclick="sandboxEditProduct()" ${test?'':'disabled'}>+ Produit test</button></div></div><div class="table-wrap"><table><thead><tr><th>Produit</th><th>Catégorie</th><th>Stock</th><th>Mini</th><th>Cible</th><th>Prix</th><th></th></tr></thead><tbody>${products.map(p=>`<tr class="${Number(p.stock)<=Number(p.min_stock)?'reorder':''}"><td><b>${esc(p.name)}</b><div class="muted">${esc(p.code)}</div></td><td>${esc(p.category)}</td><td><b>${Number(p.stock)}</b> ${esc(p.unit)}</td><td>${Number(p.min_stock)}</td><td>${Number(p.target_stock)}</td><td>${sbMoney(p.unit_price)}</td><td><button class="btn secondary" onclick="sandboxSetStock('${p.id}',${Number(p.stock)})" ${test?'':'disabled'}>Modifier stock</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Aucun produit test.</td></tr>'}</tbody></table></div>
<br><div class="card"><div class="actions" style="justify-content:space-between"><div><h3>Commandes test</h3><div class="muted">Création et réception avec mise à jour des stocks du bac à sable uniquement.</div></div><button class="btn primary" onclick="sandboxNewOrder()" ${test&&products.length?'':'disabled'}>+ Commande test</button></div></div><div class="table-wrap"><table><thead><tr><th>N°</th><th>Date</th><th>Fournisseur</th><th>État</th><th>Quantité</th><th></th></tr></thead><tbody>${orders.map(o=>{const qty=(d.order_items||[]).filter(i=>i.order_id===o.id).reduce((s,i)=>s+Number(i.quantity),0);return `<tr><td>TEST-CMD-${String(o.order_no).padStart(5,'0')}</td><td>${esc(o.order_date)}</td><td>${esc(o.supplier||'')}</td><td>${sbBadge(o.status)}</td><td>${qty}</td><td>${o.status==='commandee'?`<button class="btn primary" onclick="sandboxReceiveOrder('${o.id}')" ${test?'':'disabled'}>Réceptionner</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="6" class="muted">Aucune commande test.</td></tr>'}</tbody></table></div>
<br><div class="card"><div class="actions" style="justify-content:space-between"><div><h3>Comptabilité test</h3><div class="muted">Factures fictives, écritures fictives et contrôles comptables séparés.</div></div><button class="btn primary" onclick="sandboxNewInvoice()" ${test?'':'disabled'}>+ Facture test</button></div></div><div class="table-wrap"><table><thead><tr><th>État</th><th>Fournisseur</th><th>Facture</th><th>Date</th><th>HT</th><th>TVA</th><th>TTC</th></tr></thead><tbody>${invoices.map(i=>`<tr><td>${sbBadge(i.status)}</td><td>${esc(i.supplier||'')}</td><td>${esc(i.invoice_number||'')}</td><td>${esc(i.invoice_date||'')}</td><td>${sbMoney(i.amount_ht)}</td><td>${sbMoney(i.amount_vat)}</td><td>${sbMoney(i.amount_ttc)}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Aucune facture test.</td></tr>'}</tbody></table></div>
<br><div class="card"><h3>OD Charlemagne test</h3><div class="row"><div><label>Du</label><input id="sbOdFrom" type="date" value="${new Date().toISOString().slice(0,8)+'01'}"></div><div><label>Au</label><input id="sbOdTo" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><br><button class="btn primary" onclick="sandboxGenerateOd()" ${test?'':'disabled'}>Générer un OD test</button><p class="muted">Le fichier est uniquement simulé et porte un numéro TEST-OD-…</p></div><div class="table-wrap"><table><thead><tr><th>Lot</th><th>Période</th><th>Factures</th><th>Total TTC</th><th>État</th><th></th></tr></thead><tbody>${batches.map(b=>`<tr><td><b>${esc(b.batch_no)}</b></td><td>${esc(b.period_from)} → ${esc(b.period_to)}</td><td>${b.invoice_count}</td><td>${sbMoney(b.total_ttc)}</td><td>${sbBadge(b.status)}</td><td>${b.status==='generated'?`<button class="btn primary" onclick="sandboxMarkImported('${b.id}','${esc(b.batch_no)}')" ${test?'':'disabled'}>Simuler import Charlemagne</button>`:''} <button class="btn secondary" onclick="sandboxDownloadOd('${b.id}')">Télécharger OD test</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Aucun lot test.</td></tr>'}</tbody></table></div>`}
async function sandboxSeed(){if(!confirm('Charger un jeu de données fictives ? Les données actuelles du bac à sable seront remplacées.'))return;try{await sandboxApi('seed','POST',{});await renderSandbox()}catch(e){alert(e.message)}}
async function sandboxReset(){if(!confirm('REMETTRE LE BAC À SABLE À ZÉRO ?\n\nToutes les données test seront supprimées. Les données de production ne seront pas touchées.'))return;try{await sandboxApi('reset','POST',{});await renderSandbox()}catch(e){alert(e.message)}}
function sandboxEditProduct(){$('modal').innerHTML=`<div class="modal"><div class="box"><h2>Nouveau produit test</h2><div class="fields"><div><label>Code</label><input id="sbpCode" value="TEST-${Date.now().toString().slice(-5)}"></div><div><label>Nom</label><input id="sbpName" value="Produit test"></div><div><label>Catégorie</label><input id="sbpCat" value="Test"></div><div><label>Unité</label><input id="sbpUnit" value="pièce"></div><div><label>Prix unitaire</label><input id="sbpPrice" type="number" step="0.01" value="10"></div><div><label>Stock</label><input id="sbpStock" type="number" value="10"></div><div><label>Stock mini</label><input id="sbpMin" type="number" value="5"></div><div><label>Stock cible</label><input id="sbpTarget" type="number" value="20"></div></div><div class="actions" style="margin-top:14px"><button class="btn primary" onclick="sandboxSaveProduct()">Enregistrer TEST</button><button class="btn secondary" onclick="closeModal()">Annuler</button></div></div></div>`}
async function sandboxSaveProduct(){try{await sandboxApi('save-product','POST',{code:$('sbpCode').value,name:$('sbpName').value,category:$('sbpCat').value,unit:$('sbpUnit').value,unit_price:$('sbpPrice').value,stock:$('sbpStock').value,min_stock:$('sbpMin').value,target_stock:$('sbpTarget').value});closeModal();await renderSandbox()}catch(e){alert(e.message)}}
async function sandboxSetStock(id,current){const q=prompt('Nouveau stock TEST :',current);if(q===null)return;try{await sandboxApi('set-stock','POST',{id,stock:Number(q)});await renderSandbox()}catch(e){alert(e.message)}}
function sandboxNewOrder(){const ps=sandboxData.products||[];$('modal').innerHTML=`<div class="modal"><div class="box"><h2>Nouvelle commande TEST</h2><div class="fields"><div><label>Date</label><input id="sboDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div><label>Fournisseur</label><input id="sboSupplier" value="FOURNISSEUR TEST"></div><div><label>État</label><select id="sboStatus"><option value="brouillon">Brouillon</option><option value="commandee" selected>Commandée</option></select></div></div><div class="section-title">Articles</div>${ps.map(p=>`<div class="row" style="align-items:center;margin:7px 0"><div>${esc(p.name)} <span class="muted">stock ${Number(p.stock)}</span></div><input class="sboQty" data-id="${p.id}" type="number" min="0" placeholder="Qté"></div>`).join('')}<div class="actions" style="margin-top:14px"><button class="btn primary" onclick="sandboxSaveOrder()">Créer commande TEST</button><button class="btn secondary" onclick="closeModal()">Annuler</button></div></div></div>`}
async function sandboxSaveOrder(){const items=[...document.querySelectorAll('.sboQty')].map(x=>({product_id:x.dataset.id,quantity:Number(x.value||0)})).filter(x=>x.quantity>0);try{await sandboxApi('save-order','POST',{supplier:$('sboSupplier').value,order_date:$('sboDate').value,status:$('sboStatus').value,items});closeModal();await renderSandbox()}catch(e){alert(e.message)}}
async function sandboxReceiveOrder(id){if(!confirm('Simuler la réception ? Les stocks TEST seront augmentés.'))return;try{await sandboxApi('receive-order','POST',{id});await renderSandbox()}catch(e){alert(e.message)}}
function sandboxNewInvoice(){const rules=sandboxData.rules||[];$('modal').innerHTML=`<div class="modal"><div class="box"><h2>Nouvelle facture TEST</h2><div class="fields"><div class="full"><label>Fournisseur test</label><select id="sbiSupplier">${rules.map(r=>`<option>${esc(r.supplier_name)}</option>`).join('')}</select></div><div><label>N° facture</label><input id="sbiNumber" value="TEST-${Date.now().toString().slice(-6)}"></div><div><label>Date</label><input id="sbiDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div><label>HT</label><input id="sbiHt" type="number" step="0.01" value="100" oninput="sandboxCalcInvoice()"></div><div><label>TVA</label><input id="sbiVat" type="number" step="0.01" value="20" oninput="sandboxCalcInvoice()"></div><div><label>TTC</label><input id="sbiTtc" type="number" step="0.01" value="120"></div></div><div class="actions" style="margin-top:14px"><button class="btn primary" onclick="sandboxSaveInvoice()">Valider facture TEST</button><button class="btn secondary" onclick="closeModal()">Annuler</button></div></div></div>`}
function sandboxCalcInvoice(){if($('sbiTtc'))$('sbiTtc').value=(Number($('sbiHt').value||0)+Number($('sbiVat').value||0)).toFixed(2)}
async function sandboxSaveInvoice(){try{await sandboxApi('save-invoice','POST',{supplier:$('sbiSupplier').value,invoice_number:$('sbiNumber').value,invoice_date:$('sbiDate').value,amount_ht:$('sbiHt').value,amount_vat:$('sbiVat').value,amount_ttc:$('sbiTtc').value});closeModal();await renderSandbox()}catch(e){alert(e.message)}}
async function sandboxGenerateOd(){try{const j=await sandboxApi('generate-od','POST',{from:$('sbOdFrom').value,to:$('sbOdTo').value});sandboxDownloadText(j.od_text,j.batch_no+'.txt');await renderSandbox()}catch(e){alert(e.message)}}
function sandboxDownloadText(text,name){const b=new Blob([text],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function sandboxDownloadOd(id){const b=(sandboxData.batches||[]).find(x=>x.id===id);if(b)sandboxDownloadText(b.od_text,b.batch_no+'.txt')}
async function sandboxMarkImported(id,no){if(!confirm(`Simuler l’import du lot ${no} dans Charlemagne ?\n\nCela ne contacte pas Charlemagne et ne touche aucune donnée réelle.`))return;try{await sandboxApi('batch-imported','POST',{id});await renderSandbox()}catch(e){alert(e.message)}}
