(()=>{
'use strict';
const SUB_API='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/subcategory-api';
const SUB_FILTER_KEY='college_admin_product_filter_subcategory';
async function subApi(action='list',method='GET',body){const r=await fetch(SUB_API+'?action='+encodeURIComponent(action),{method,headers:{'content-type':'application/json',authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Réponse invalide'}));if(!r.ok)throw new Error(j.error||'Erreur sous-catégories');return j}
async function loadSubs(){if(!db)return;const j=await subApi('list');db.subcategories=j.subcategories||[];const by=new Map((j.product_subcategories||[]).map(x=>[x.id,x.subcategory_id||null]));db.products.forEach(p=>p.subcategory_id=by.get(p.id)??p.subcategory_id??null)}
const baseRefresh=refresh;
refresh=async function(){await baseRefresh();try{await loadSubs();render()}catch(e){console.warn('Sous-catégories indisponibles',e)}};
const subById=id=>(db.subcategories||[]).find(x=>x.id===id);
const subsForCat=id=>(db.subcategories||[]).filter(x=>x.category_id===id&&x.active!==false).sort((a,b)=>Number(a.sort_order)-Number(b.sort_order)||String(a.name).localeCompare(String(b.name),'fr'));
window.manageSubcategories=function(categoryId){const c=catById(categoryId),rows=subsForCat(categoryId);modal(`Sous-catégories — ${c?.name||''}`,`<div class="actions" style="margin-bottom:12px"><button class="btn primary" type="button" onclick="editSubcategory('${categoryId}')">+ Ajouter une sous-catégorie</button></div><div class="table-wrap"><table style="min-width:0"><thead><tr><th>Nom</th><th>Code</th><th>Ordre</th><th>Produits</th><th></th></tr></thead><tbody>${rows.length?rows.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.code)}</td><td>${Number(s.sort_order||0)}</td><td>${db.products.filter(p=>p.active&&p.subcategory_id===s.id).length}</td><td><button class="btn secondary" type="button" onclick="editSubcategory('${categoryId}','${s.id}')">Modifier</button> <button class="btn danger" type="button" onclick="deleteSubcategory('${s.id}')">Supprimer</button></td></tr>`).join(''):'<tr><td colspan="5" class="muted">Aucune sous-catégorie.</td></tr>'}</tbody></table></div>`,()=>closeModal());$('msave').textContent='Fermer'};
window.editSubcategory=function(categoryId,id=''){const s=id?subById(id):null,c=catById(categoryId);modal(s?'Modifier la sous-catégorie':'Nouvelle sous-catégorie',`<div class="fields"><div><label>Catégorie</label><input value="${esc(c?.name||'')}" disabled></div><div><label>Nom</label><input id="subName" value="${esc(s?.name||'')}"></div><div><label>Code</label><input id="subCode" value="${esc(s?.code||'')}"></div><div><label>Ordre</label><input id="subOrder" type="number" min="0" value="${Number(s?.sort_order??100)}"></div></div>`,async()=>{try{await subApi('save','POST',{id,category_id:categoryId,name:$('subName').value,code:$('subCode').value,sort_order:Number($('subOrder').value),active:true});closeModal();await loadSubs();manageSubcategories(categoryId)}catch(e){$('mstatus').textContent=e.message}})};
window.deleteSubcategory=async function(id){const s=subById(id);if(!s||!confirm(`Supprimer la sous-catégorie « ${s.name} » ?\n\nLes produits resteront dans leur catégorie principale.`))return;try{await subApi('delete','POST',{id});await loadSubs();manageSubcategories(s.category_id)}catch(e){alert(e.message)}};
renderCategories=function(){$('content').innerHTML=`<div class="toolbar"><button class="btn primary" onclick="editCategory()">Ajouter une catégorie</button><button class="btn secondary" onclick="show('apps')">Sites et QR codes</button></div><div class="table-wrap"><table><thead><tr><th>Nom</th><th>Code</th><th>Mode app</th><th>Sous-catégories</th><th>Active</th><th>Site</th><th></th></tr></thead><tbody>${db.categories.map(c=>{const a=siteForCategory(c.id),n=subsForCat(c.id).length;return `<tr><td>${esc(c.name)}</td><td>${esc(c.code)}</td><td>${esc(c.app_mode)}</td><td><button class="btn secondary" onclick="manageSubcategories('${c.id}')">${n} sous-catégorie${n>1?'s':''}</button></td><td>${c.active?'Oui':'Non'}</td><td>${a?'<span class="pill">Créé</span>':'<span class="muted">Non créé</span>'}</td><td><button class="btn secondary" onclick="editCategory('${c.id}')">Modifier</button> <button class="btn danger" onclick="resetCat('${c.id}')">Stock à zéro</button></td></tr>`}).join('')}</tbody></table></div>`};
renderProducts=function(){let savedCat=localStorage.getItem(PRODUCT_FILTER_CATEGORY_KEY)||'',savedSub=localStorage.getItem(SUB_FILTER_KEY)||'',savedSearch=localStorage.getItem(PRODUCT_FILTER_SEARCH_KEY)||'';if(savedCat&&!db.categories.some(c=>c.id===savedCat))savedCat='';if(savedSub&&!subById(savedSub))savedSub='';const cats='<option value="">Toutes catégories</option>'+db.categories.map(c=>`<option value="${c.id}" ${c.id===savedCat?'selected':''}>${esc(c.name)}</option>`).join(''),subs='<option value="">Toutes sous-catégories</option><option value="__none__" '+(savedSub==='__none__'?'selected':'')+'>Sans sous-catégorie</option>'+(db.subcategories||[]).filter(s=>s.active!==false&&(!savedCat||s.category_id===savedCat)).map(s=>`<option value="${s.id}" ${s.id===savedSub?'selected':''}>${esc(s.name)}</option>`).join('');$('content').innerHTML=`<div class="toolbar"><button class="btn primary" onclick="editProduct()">Ajouter un produit</button><select id="pf" onchange="productCategoryFilterChanged()">${cats}</select><select id="psub" onchange="filterProducts()">${subs}</select><input id="ps" placeholder="Rechercher" value="${esc(savedSearch)}" oninput="filterProducts()"></div><div class="table-wrap"><table><thead><tr><th>Produit</th><th>Catégorie</th><th>Sous-catégorie</th><th>Prix</th><th>Mini</th><th>Cible</th><th>Stock actuel</th><th></th></tr></thead><tbody id="prodBody"></tbody></table></div>`;filterProducts(false)};
window.productCategoryFilterChanged=function(){localStorage.setItem(PRODUCT_FILTER_CATEGORY_KEY,$('pf').value);localStorage.setItem(SUB_FILTER_KEY,'');renderProducts()};
filterProducts=function(saveState=true){const f=$('pf')?.value||'',sf=$('psub')?.value||'',raw=$('ps')?.value||'',s=raw.toLowerCase();if(saveState){localStorage.setItem(PRODUCT_FILTER_CATEGORY_KEY,f);localStorage.setItem(SUB_FILTER_KEY,sf);localStorage.setItem(PRODUCT_FILTER_SEARCH_KEY,raw)}$('prodBody').innerHTML=db.products.filter(p=>p.active!==false&&(!f||p.category_id===f)&&(!sf||(sf==='__none__'?!p.subcategory_id:p.subcategory_id===sf))&&(!s||p.name.toLowerCase().includes(s)||p.code.toLowerCase().includes(s))).map(p=>`<tr><td>${esc(p.name)}<div class="muted">${esc(p.code)}</div></td><td>${esc(catById(p.category_id)?.name||'')}</td><td>${esc(subById(p.subcategory_id)?.name||'—')}</td><td>${Number(p.unit_price).toFixed(2)} €</td><td>${p.min_stock}</td><td>${p.target_stock}</td><td><b>${bal(p.id)}</b></td><td><button class="btn secondary" onclick="editProduct('${p.id}')">Modifier</button> <button class="btn secondary" onclick="setStock('${p.id}')">Stock</button> <button class="btn danger" onclick="deleteProduct('${p.id}')">Supprimer</button></td></tr>`).join('')};
function productSubOptions(categoryId,selected=''){return '<option value="">Sans sous-catégorie</option>'+subsForCat(categoryId).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${esc(s.name)}</option>`).join('')}
window.productCategoryModalChanged=function(){if($('psubcat'))$('psubcat').innerHTML=productSubOptions($('pcat').value,'')};
editProduct=function(id){const p=id?db.products.find(x=>x.id===id):{},cat=p.category_id||db.categories[0]?.id||'';modal(id?'Modifier le produit':'Nouveau produit',`<div class="fields"><div><label>Nom</label><input id="pname" value="${esc(p.name||'')}"></div><div><label>Code</label><input id="pcode" value="${esc(p.code||'')}"></div><div><label>Catégorie</label><select id="pcat" onchange="productCategoryModalChanged()">${db.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div><label>Sous-catégorie</label><select id="psubcat"></select></div><div><label>Unité</label><input id="punit" value="${esc(p.unit||'pièce')}"></div><div><label>Prix unitaire</label><input id="pprice" type="number" step="0.01" value="${p.unit_price??0}"></div><div><label>Stock mini</label><input id="pmin" type="number" value="${p.min_stock??0}"></div><div><label>Stock cible</label><input id="ptarget" type="number" value="${p.target_stock??0}"></div><div><label>Stock de départ</label><input id="pinitial" type="number" value="${p.initial_stock??0}"></div></div>`,async()=>{try{const r=await api('save-product','POST',{id,name:$('pname').value,code:$('pcode').value,category_id:$('pcat').value,unit:$('punit').value,unit_price:$('pprice').value,min_stock:$('pmin').value,target_stock:$('ptarget').value,initial_stock:$('pinitial').value,active:true});await subApi('assign-product','POST',{product_id:r.item.id,subcategory_id:$('psubcat').value||null});closeModal();await refresh()}catch(e){$('mstatus').textContent=e.message}});$('pcat').value=cat;$('psubcat').innerHTML=productSubOptions(cat,p.subcategory_id||'')};
if(token&&db)loadSubs().then(()=>render()).catch(console.warn);
})();
