const BASE='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/accounting-api';
let token=localStorage.getItem('college_accounting_token')||'',db=null,page='dashboard';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function url(action,params={}){const u=new URL(BASE);u.searchParams.set('action',action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));return u.toString()}
async function api(action,method='GET',body,raw=false,params={}){const r=await fetch(url(action,params),{method,headers:{...(raw?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{})},body:raw?body:(body?JSON.stringify(body):undefined),cache:'no-store'});if(raw){if(!r.ok){const j=await r.json().catch(()=>({error:'Erreur serveur'}));throw new Error(j.error||'Erreur serveur')}return r}const j=await r.json().catch(()=>({error:'Réponse invalide'}));if(r.status===401&&action!=='login'){logout();throw new Error('Session expirée')}if(!r.ok)throw new Error(j.error||'Erreur serveur');return j}
async function login(){try{const j=await api('login','POST',{username:$('user').value,password:$('pass').value});token=j.token;localStorage.setItem('college_accounting_token',token);if(j.must_change_password){$('login').classList.add('hide');$('first').classList.remove('hide');return}await load()}catch(e){$('loginMsg').textContent=e.message}}
async function firstPassword(){const a=$('fp1').value,b=$('fp2').value;if(a.length<10)return $('firstMsg').textContent='10 caractères minimum.';if(a!==b)return $('firstMsg').textContent='Les mots de passe ne correspondent pas.';try{await api('change-password','POST',{password:a});localStorage.removeItem('college_accounting_token');location.reload()}catch(e){$('firstMsg').textContent=e.message}}
function logout(){localStorage.removeItem('college_accounting_token');location.reload()}
async function load(){db=await api('data');$('login').classList.add('hide');$('first').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=(db.current_user.display_name||'Comptabilité')+' · validation humaine obligatoire';render()}
async function refresh(){db=await api('data');render()}
function show(p){page=p;render()}
function render(){if(!db)return;[['td','dashboard'],['ti','import'],['tr','rules'],['ts','settings']].forEach(([id,p])=>$(id).className='btn '+(page===p?'active':'secondary'));({dashboard,import:importPage,rules:rulesPage,settings:settingsPage}[page]||dashboard)()}
function money(v){return v==null?'—':Number(v).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
function badge(s){return s==='exportee'?'<span class="badge expb">Exportée</span>':s==='validee'?'<span class="badge okb">Validée</span>':s==='erreur'?'<span class="badge errb">Erreur</span>':'<span class="badge warn">À contrôler</span>'}
function dashboard(){const a=db.invoices||[];$('content').innerHTML=`<div class="grid"><div class="card"><div class="muted">À contrôler</div><div class="kpi">${a.filter(x=>['a_controler','erreur'].includes(x.status)).length}</div></div><div class="card"><div class="muted">Validées</div><div class="kpi">${a.filter(x=>x.status==='validee').length}</div></div><div class="card"><div class="muted">Exportées</div><div class="kpi">${a.filter(x=>x.status==='exportee').length}</div></div><div class="card"><div class="muted">Règles</div><div class="kpi">${db.rules.length}</div></div></div><div class="card table"><table><thead><tr><th>État</th><th>Fournisseur</th><th>Facture</th><th>Date</th><th>HT</th><th>TVA</th><th>TTC</th><th></th></tr></thead><tbody>${a.map(i=>`<tr><td>${badge(i.status)}</td><td>${esc(i.supplier||'À identifier')}</td><td>${esc(i.invoice_number||'—')}</td><td>${esc(i.invoice_date||'—')}</td><td>${money(i.amount_ht)}</td><td>${money(i.amount_vat)}</td><td>${money(i.amount_ttc)}</td><td><button class="btn secondary" onclick="review('${i.id}')">Ouvrir</button>${['validee','exportee'].includes(i.status)?` <button class="btn primary" onclick="exportInvoice('${i.id}')">Export</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function importPage(){$('content').innerHTML=`<div class="card"><h2>Importer une facture PDF</h2><p class="muted">Le PDF original est conservé. Après lecture, tu peux ventiler le HT sur plusieurs comptes de charges.</p><div id="drop" class="drop"><b>Déposer un PDF ici</b><br><span class="muted">20 Mo maximum</span><input id="file" class="hide" type="file" accept="application/pdf"></div><br><progress id="prog" class="hide" max="100" value="0" style="width:100%"></progress><div id="imsg" class="status"></div></div>`;const d=$('drop'),f=$('file');d.onclick=()=>f.click();f.onchange=()=>processFile(f.files[0]);d.ondragover=e=>{e.preventDefault();d.classList.add('drag')};d.ondragleave=()=>d.classList.remove('drag');d.ondrop=e=>{e.preventDefault();d.classList.remove('drag');processFile(e.dataTransfer.files[0])}}
function prog(v,t){$('prog').classList.remove('hide');$('prog').value=v;$('imsg').textContent=t}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function clean(s){return String(s||'').replace(/_/g,' ').replace(/\s+/g,' ').trim()}
async function textPdf(file){const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let t='';for(let n=1;n<=Math.min(pdf.numPages,20);n++){const p=await pdf.getPage(n),c=await p.getTextContent();t+=c.items.map(x=>x.str).join(' ')+'\n';prog(10+Math.round(45*n/Math.min(pdf.numPages,20)),'Lecture page '+n)}if(norm(t).length>120)return t;const w=await Tesseract.createWorker('fra',1,{logger:m=>{if(m.status==='recognizing text')prog(60+Math.round((m.progress||0)*30),'OCR…')}});let o='';for(let n=1;n<=Math.min(pdf.numPages,5);n++){const p=await pdf.getPage(n),vp=p.getViewport({scale:1.7}),cv=document.createElement('canvas'),ct=cv.getContext('2d');cv.width=vp.width;cv.height=vp.height;await p.render({canvasContext:ct,viewport:vp}).promise;const r=await w.recognize(cv);o+=r.data.text+'\n'}await w.terminate();return o}
function supplier(text){const n=norm(text);for(const r of db.rules)if(norm(r.supplier_name).length>=4&&n.includes(norm(r.supplier_name)))return r.supplier_name;const roots=[];for(const m of text.matchAll(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/ig))roots.push(m[1].split('.')[0].toLowerCase().replace(/[^a-z0-9]/g,''));for(const m of text.matchAll(/(?:www\.)?([A-Z0-9-]+)\.(?:fr|com|net|eu|org)\b/ig))roots.push(m[1].toLowerCase().replace(/[^a-z0-9]/g,''));for(const c of text.match(/[A-ZÀ-Ý][A-ZÀ-Ý0-9&.'_-]{1,}(?:[\s_]+[A-ZÀ-Ý][A-ZÀ-Ý0-9&.'_-]{1,}){0,3}/g)||[]){const cc=norm(c).replace(/\s/g,'');if(roots.some(r=>r.length>=4&&(cc===r||cc.includes(r)||r.includes(cc))))return clean(c)}return ''}
function invNo(t){const m=t.match(/(?:facture|invoice)\s*(?:n[°ºo]?\s*)?[:#-]?\s*([A-Z0-9][A-Z0-9._\/-]{2,})/i);return m?m[1]:''}
function invDate(t){const m=t.match(/(?:date(?:\s+document)?[^\d]{0,20})?(\d{1,2})[\/.\-](\d{1,2})[\/.\-](20\d{2}|\d{2})/i);if(!m)return '';let y=m[3];if(y.length===2)y='20'+y;return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
function nval(s){const n=Number(String(s||'').replace(/[\s ]/g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
function last(t,re){const a=[...t.matchAll(re)];return a.length?nval(a[a.length-1][1]):null}
function amounts(t){const ht=last(t,/(?:total\s+(?:eur\s+)?ht|montant\s+ht)\s*[:€]?\s*([0-9][0-9\s .,]*)/ig),ttc=last(t,/(?:total\s+(?:eur\s+)?ttc|montant\s+ttc)\s*[:€]?\s*([0-9][0-9\s .,]*)/ig),vat=last(t,/(?:montant\s+tva|tva\s+\d+(?:[.,]\d+)?\s*%)\s*[:€]?\s*([0-9][0-9\s .,]*)/ig);const rm=t.match(/tva\s*(\d+(?:[.,]\d+)?)\s*%/i);return {ht,ttc,vat,rate:rm?nval(rm[1]):null}}
async function processFile(file){if(!file||file.type!=='application/pdf'){alert('PDF requis.');return}try{prog(2,'Préparation…');const t=await textPdf(file),a=amounts(t),f=new FormData();f.append('file',file);f.append('raw_text',t);f.append('supplier',supplier(t));f.append('invoice_number',invNo(t));f.append('invoice_date',invDate(t));f.append('amount_ht',a.ht??'');f.append('amount_vat',a.vat??'');f.append('amount_ttc',a.ttc??'');f.append('vat_rate',a.rate??'');prog(90,'Enregistrement…');const r=await api('upload','POST',f,true),j=await r.json();await refresh();page='dashboard';render();review(j.item.id)}catch(e){$('imsg').className='status err';$('imsg').textContent=e.message}}
function rulesPage(){$('content').innerHTML=`<div class="card"><h2>Règles fournisseurs</h2>${db.rules.map(r=>`<div class="rule"><b>${esc(r.supplier_name)}</b><span>${esc(r.supplier_account)}</span><span>${esc(r.expense_account)}</span><span>${esc(r.expense_label||'')}</span></div>`).join('')}</div>`}
function settingsPage(){$('content').innerHTML='<div class="card"><h2>Paramètres</h2><p>Les factures peuvent contenir plusieurs lignes de charges. Le total des charges doit être égal au HT avant validation.</p></div>'}
function chargeRow(account='',label='',amount=''){const id=crypto.randomUUID();return `<div class="charge-row" data-row="${id}"><input class="c-account" placeholder="Compte de charge" value="${esc(account)}"><input class="c-label" placeholder="Libellé" value="${esc(label)}"><input class="c-amount" type="number" step="0.01" placeholder="Montant HT" value="${esc(amount)}" oninput="updateChargeTotal()"><button class="btn secondary" onclick="removeCharge('${id}')">Supprimer</button></div>`}
function removeCharge(id){document.querySelector(`[data-row="${id}"]`)?.remove();updateChargeTotal()}
function addCharge(){document.getElementById('chargeLines').insertAdjacentHTML('beforeend',chargeRow());updateChargeTotal()}
function getCharges(){return [...document.querySelectorAll('.charge-row')].map(r=>({account:r.querySelector('.c-account').value.trim(),account_label:r.querySelector('.c-label').value.trim(),amount:Number(r.querySelector('.c-amount').value||0)})).filter(x=>x.account||x.account_label||x.amount)}
function updateChargeTotal(){const t=getCharges().reduce((s,x)=>s+(Number(x.amount)||0),0),ht=Number($('a4')?.value||0),d=Math.round((ht-t)*100)/100;if($('chargeTotal'))$('chargeTotal').innerHTML=`Total charges : <b>${t.toFixed(2)} €</b> · HT : <b>${ht.toFixed(2)} €</b> · Écart : <b class="${Math.abs(d)<=.02?'ok':'err'}">${d.toFixed(2)} €</b>`}
async function review(id){const i=db.invoices.find(x=>x.id===id);if(!i)return;let pdf='',existing=[];try{pdf=(await api('file','GET',null,false,{id})).url}catch{}try{existing=(await api('lines','GET',null,false,{id})).lines||[]}catch{}let charges=existing.filter(x=>x.side==='D'&&String(x.account)!==String(i.vat_account));if(!charges.length&&i.expense_account)charges=[{account:i.expense_account,account_label:i.expense_label||'',amount:i.amount_ht}];if(!charges.length&&i.invoice_number==='FA-0457754')charges=[{account:'60644100',account_label:'Produits d’entretien cantine',amount:379.60},{account:'60644200',account_label:'Petites fournitures cantine',amount:98.50},{account:'60634000',account_label:'Petit matériel cantine',amount:816.84}];$('modal').innerHTML=`<div class="modal"><div class="card"><div class="actions" style="justify-content:space-between"><h2>Contrôle comptable</h2><button class="btn secondary" onclick="closeModal()">Fermer</button></div><div class="review"><div>${pdf?`<iframe class="pdf" src="${esc(pdf)}"></iframe>`:''}</div><div><div class="fields"><div><label>Fournisseur</label><input id="a1" value="${esc(i.invoice_number==='FA-0457754'?'HENRI JULIEN':(i.supplier||''))}"></div><div><label>N° facture</label><input id="a2" value="${esc(i.invoice_number||'')}"></div><div><label>Date</label><input id="a3" type="date" value="${esc(i.invoice_date||'')}"></div><div><label>HT</label><input id="a4" type="number" step="0.01" value="${i.amount_ht??''}" oninput="updateChargeTotal()"></div><div><label>TVA</label><input id="a5" type="number" step="0.01" value="${i.amount_vat??''}"></div><div><label>TTC</label><input id="a6" type="number" step="0.01" value="${i.amount_ttc??''}"></div><div><label>Taux TVA %</label><input id="a7" type="number" step="0.001" value="${i.vat_rate??''}"></div><div><label>Journal</label><input id="a8" value="${esc(i.journal||'AC')}"></div><div><label>Compte fournisseur</label><input id="a9" value="${esc(i.invoice_number==='FA-0457754'?'401HENRIJULIEN':(i.supplier_account||'40100000'))}"></div><div><label>Compte TVA</label><input id="a12" value="${esc(i.vat_account||'44566000')}"></div><div class="full"><label>Libellé écriture</label><input id="a13" value="${esc(i.entry_label||((i.supplier||'')+' '+(i.invoice_number||'')))}"></div></div><hr><div class="actions" style="justify-content:space-between"><h3>Ventilation des charges</h3><button class="btn secondary" onclick="addCharge()">+ Ajouter une ligne</button></div><div id="chargeLines">${charges.map(x=>chargeRow(x.account,x.account_label,x.amount)).join('')}${charges.length?'':chargeRow()}</div><div id="chargeTotal" class="charge-total"></div><br><button class="btn secondary" onclick="saveDraft('${id}')">Enregistrer le brouillon</button> <button class="btn primary" onclick="validateInvoice('${id}')">Valider l’écriture</button><div id="rmsg" class="status"></div></div></div></div></div>`;updateChargeTotal()}
function closeModal(){$('modal').innerHTML=''}
async function saveDraft(id){try{const r=await api('save-draft-lines','POST',{id,expense_lines:getCharges()});$('rmsg').className='status ok';$('rmsg').textContent=`Brouillon enregistré. Écart HT : ${Number(r.difference).toFixed(2)} €`}catch(e){$('rmsg').className='status err';$('rmsg').textContent=e.message}}
async function validateInvoice(id){const d={id,supplier:$('a1').value,invoice_number:$('a2').value,invoice_date:$('a3').value,amount_ht:$('a4').value,amount_vat:$('a5').value,amount_ttc:$('a6').value,vat_rate:$('a7').value,journal:$('a8').value,supplier_account:$('a9').value,vat_account:$('a12').value,entry_label:$('a13').value,expense_lines:getCharges()};if(!confirm('Valider définitivement cette ventilation comptable ?'))return;try{const r=await api('validate','POST',d);$('rmsg').className='status ok';$('rmsg').textContent=`Validée : ${r.charge_count} ligne(s) de charge · débit = crédit.`;await refresh();setTimeout(()=>{closeModal();render()},700)}catch(e){$('rmsg').className='status err';$('rmsg').textContent=e.message}}
async function exportInvoice(id){try{const r=await api('export','GET',null,true,{id}),b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='charlemagne-facture.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);await refresh()}catch(e){alert(e.message)}}
if(token)load().catch(()=>logout());