const RULES_BASE='https://zreegtzfpwrjgdhhunxx.supabase.co/functions/v1/accounting-rules';
let rulesCache=[];
async function rulesApi(action,method='GET',body){const u=new URL(RULES_BASE);u.searchParams.set('action',action);const r=await fetch(u.toString(),{method,headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({error:'Réponse invalide'}));if(r.status===401){logout();throw new Error('Session expirée')}if(!r.ok)throw new Error(j.error||'Erreur serveur');return j}

rulesPage=function(){
  $('content').innerHTML='<div class="card"><h2>Règles fournisseurs</h2><div class="muted">Chargement…</div></div>';
  loadRulesPage().catch(e=>{$('content').innerHTML=`<div class="card"><h2>Règles fournisseurs</h2><div class="err">${esc(e.message)}</div></div>`});
}
async function loadRulesPage(){const j=await rulesApi('list');rulesCache=j.rules||[];const rules=[...rulesCache].sort((a,b)=>String(a.supplier_name||'').localeCompare(String(b.supplier_name||''),'fr'));const known=rules.filter(r=>(r.charge_accounts||[]).length).length,pending=rules.length-known;$('content').innerHTML=`<div class="card"><div class="actions" style="justify-content:space-between"><div><h2>Règles fournisseurs</h2><div class="muted">${rules.length} fournisseurs actifs · ${known} avec au moins un compte de charge · ${pending} sans compte de charge.</div></div><div class="actions"><input id="ruleSearch" style="max-width:320px" placeholder="Rechercher fournisseur ou compte"><button class="btn primary" onclick="editSupplierRule()">+ Nouveau fournisseur</button></div></div></div><div class="card table"><table><thead><tr><th>Fournisseur</th><th>Compte fournisseur</th><th>Comptes de charges autorisés</th><th>TVA</th><th>Journal</th><th></th></tr></thead><tbody id="rulesBody">${rules.map(ruleRow).join('')}</tbody></table></div>`;const q=$('ruleSearch');if(q)q.oninput=()=>filterRules(q.value)}
function ruleRow(r){const charges=r.charge_accounts||[];const search=[r.supplier_name,r.supplier_account,r.vat_account,r.journal,...charges.flatMap(c=>[c.expense_account,c.expense_label])].join(' ').toLowerCase();const html=charges.length?charges.map(c=>`<div><b>${esc(c.expense_account)}</b> · ${esc(c.expense_label||'')}${c.is_default?' <span class="badge okb">Défaut</span>':''}</div>`).join(''):'<span class="badge warn">Aucun compte</span>';return `<tr data-rule-search="${esc(search)}"><td><b>${esc(r.supplier_name||'')}</b></td><td>${esc(r.supplier_account||'')}</td><td>${html}</td><td>${esc(r.vat_account||'44566000')}</td><td>${esc(r.journal||'AC')}</td><td><button class="btn secondary" onclick="editSupplierRule('${r.id}')">Modifier</button></td></tr>`}
function filterRules(v){const n=String(v||'').toLowerCase().trim();document.querySelectorAll('#rulesBody tr').forEach(tr=>{tr.style.display=!n||String(tr.dataset.ruleSearch||'').includes(n)?'':'none'})}
function supplierChargeRow(c={},idx=0){const id=crypto.randomUUID();return `<div class="supplier-charge-row" data-charge-row="${id}" style="display:grid;grid-template-columns:1fr 1.5fr auto auto;gap:8px;margin:8px 0;align-items:center"><input class="sr-account" placeholder="Compte de charge" value="${esc(c.expense_account||'')}"><input class="sr-label" placeholder="Libellé" value="${esc(c.expense_label||'')}"><label style="display:flex;gap:6px;align-items:center;white-space:nowrap"><input class="sr-default" type="radio" name="defaultCharge" ${c.is_default?'checked':''} style="width:auto"> Par défaut</label><button class="btn secondary" onclick="removeSupplierCharge('${id}')">Supprimer</button></div>`}
function addSupplierCharge(){const box=$('supplierChargeRows');box.insertAdjacentHTML('beforeend',supplierChargeRow({},box.children.length));}
function removeSupplierCharge(id){document.querySelector(`[data-charge-row="${id}"]`)?.remove()}
function editSupplierRule(id=''){const r=id?rulesCache.find(x=>x.id===id):null;const charges=r?.charge_accounts||[];$('modal').innerHTML=`<div class="modal"><div class="card" style="max-width:900px"><div class="actions" style="justify-content:space-between"><h2>${r?'Modifier le fournisseur':'Nouveau fournisseur'}</h2><button class="btn secondary" onclick="closeModal()">Fermer</button></div><div class="fields"><div class="full"><label>Nom du fournisseur</label><input id="srName" value="${esc(r?.supplier_name||'')}"></div><div><label>Compte fournisseur</label><input id="srSupplierAccount" value="${esc(r?.supplier_account||'401')}"></div><div><label>Compte TVA</label><input id="srVat" value="${esc(r?.vat_account||'44566000')}"></div><div><label>Journal</label><input id="srJournal" value="${esc(r?.journal||'AC')}"></div></div><hr><div class="actions" style="justify-content:space-between"><div><h3>Comptes de charges</h3><div class="muted">Tu peux en associer plusieurs. Le compte marqué « Par défaut » sera proposé automatiquement à l’import.</div></div><button class="btn secondary" onclick="addSupplierCharge()">+ Ajouter un compte</button></div><div id="supplierChargeRows">${charges.map((c,i)=>supplierChargeRow(c,i)).join('')}</div>${charges.length?'':'<div class="muted" id="noChargeHint">Aucun compte de charge pour le moment.</div>'}<br><button class="btn primary" onclick="saveSupplierRule('${id}')">Enregistrer</button><div id="srMsg" class="status"></div></div></div>`}
function collectSupplierCharges(){return [...document.querySelectorAll('.supplier-charge-row')].map(r=>({expense_account:r.querySelector('.sr-account').value.trim(),expense_label:r.querySelector('.sr-label').value.trim(),is_default:r.querySelector('.sr-default').checked})).filter(x=>x.expense_account)}
async function saveSupplierRule(id=''){const body={id,supplier_name:$('srName').value.trim(),supplier_account:$('srSupplierAccount').value.trim(),vat_account:$('srVat').value.trim(),journal:$('srJournal').value.trim(),charge_accounts:collectSupplierCharges()};const msg=$('srMsg');try{msg.className='status';msg.textContent='Enregistrement…';await rulesApi('save','POST',body);msg.className='status ok';msg.textContent='Fournisseur enregistré.';await refresh();await loadRulesPage();setTimeout(closeModal,350)}catch(e){msg.className='status err';msg.textContent=e.message}}
