(()=>{
'use strict';
const APP_ROOT='https://edm28contact-wq.github.io/gestion-college-app/college/?id=';
const QR_LIB='https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js';
const PDF_LIB='https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js';
let loading=null;
function safeFileName(s){return String(s||'application').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase()||'application'}
function appUrl(a){return APP_ROOT+encodeURIComponent(a.public_id)}
function loadScript(src,test){if(test())return Promise.resolve();return new Promise((resolve,reject)=>{const old=[...document.scripts].find(s=>s.src===src);if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(new Error('Bibliothèque indisponible.')),{once:true});return}const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Bibliothèque indisponible.'));document.head.appendChild(s)})}
async function ensureLibs(){if(loading)return loading;loading=Promise.all([loadScript(QR_LIB,()=>!!window.QRCode?.toDataURL),loadScript(PDF_LIB,()=>!!window.jspdf?.jsPDF)]).catch(e=>{loading=null;throw e});return loading}
async function qrDataUrl(a,size=900){await ensureLibs();return QRCode.toDataURL(appUrl(a),{errorCorrectionLevel:'H',margin:2,width:size,color:{dark:'#000000',light:'#ffffff'}})}
function modalHtml(a,data){const u=appUrl(a);return `<div class="modal"><div class="box" style="width:min(680px,100%);text-align:center"><div class="top" style="text-align:left"><div><h2 style="margin:0">${esc(a.name||a.code||'Application')}</h2><div class="muted">QR code individuel · ${esc(a.code||'')}</div></div><button class="btn secondary" onclick="closeModal()">Fermer</button></div><div style="padding:18px 0"><img src="${data}" alt="QR code ${esc(a.name||'application')}" style="width:min(360px,85vw);height:auto;border:12px solid #fff;box-shadow:0 0 0 1px #dfe4e8;border-radius:8px"></div><div style="font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;word-break:break-all;background:#f6f8fa;padding:10px;border-radius:8px;text-align:left">${esc(u)}</div><div class="muted" style="margin:12px 0">Le PDF A4 est prêt à être imprimé et affiché près du poste concerné. Le QR code ouvre directement cette application.</div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="printAppQrPdf('${a.id}')">Ouvrir / imprimer le PDF</button><button class="btn success" onclick="downloadAppQrPdf('${a.id}')">Télécharger le PDF</button></div><div id="qrAdminStatus" class="status"></div></div></div>`}
window.openAppQr=async id=>{const a=appById(id);if(!a)return;document.getElementById('modal').innerHTML='<div class="modal"><div class="box"><h2>Préparation du QR code…</h2><div class="muted">Génération en cours.</div></div></div>';try{const data=await qrDataUrl(a,720);document.getElementById('modal').innerHTML=modalHtml(a,data)}catch(e){document.getElementById('modal').innerHTML=`<div class="modal"><div class="box"><h2>QR code indisponible</h2><div class="status err">${esc(e.message||'Erreur de génération.')}</div><button class="btn secondary" onclick="closeModal()">Fermer</button></div></div>`}};
async function buildPdf(a){await ensureLibs();const data=await qrDataUrl(a,1200),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),u=appUrl(a);const accent=/^#[0-9a-f]{6}$/i.test(String(a.color||''))?String(a.color):'#243447',rgb=[parseInt(accent.slice(1,3),16),parseInt(accent.slice(3,5),16),parseInt(accent.slice(5,7),16)];doc.setFillColor(...rgb);doc.rect(0,0,210,28,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('SOCIETE COLLEGE',105,11,{align:'center'});doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text('Acces direct a une application de gestion',105,19,{align:'center'});doc.setTextColor(25,35,45);doc.setFont('helvetica','bold');doc.setFontSize(20);const title=doc.splitTextToSize(String(a.name||a.code||'Application'),170);doc.text(title,105,42,{align:'center'});const qrY=Math.max(58,45+title.length*7);doc.addImage(data,'PNG',55,qrY,100,100);let y=qrY+113;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('Scannez ce QR code pour ouvrir l\'application',105,y,{align:'center'});y+=8;doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text('Le QR code ouvre directement l\'application publique correspondante.',105,y,{align:'center'});y+=10;doc.setDrawColor(220,225,230);doc.line(25,y,185,y);y+=8;doc.setFontSize(9);doc.setTextColor(90,100,110);doc.text('Code application : '+String(a.code||''),25,y);y+=6;doc.text(doc.splitTextToSize(u,160),25,y);doc.setFontSize(8);doc.text('Document genere depuis l\'Administration College.',105,287,{align:'center'});return doc}
window.downloadAppQrPdf=async id=>{const a=appById(id);if(!a)return;const s=document.getElementById('qrAdminStatus');if(s){s.className='status';s.textContent='Création du PDF…'}try{const doc=await buildPdf(a);doc.save('qr-'+safeFileName(a.name||a.code)+'.pdf');if(s){s.className='status ok';s.textContent='PDF créé.'}}catch(e){if(s){s.className='status err';s.textContent=e.message||'Impossible de créer le PDF.'}}};
window.printAppQrPdf=async id=>{const a=appById(id);if(!a)return;const popup=window.open('about:blank','_blank'),s=document.getElementById('qrAdminStatus');if(s){s.className='status';s.textContent='Préparation du PDF…'}try{const doc=await buildPdf(a),url=doc.output('bloburl');if(!popup)throw new Error('Le navigateur a bloqué l’ouverture du PDF. Utilisez « Télécharger le PDF ».');popup.location.href=url;if(s){s.className='status ok';s.textContent='PDF ouvert. Utilisez ensuite Imprimer dans le lecteur PDF.'}}catch(e){if(popup)popup.close();if(s){s.className='status err';s.textContent=e.message||'Impossible d’ouvrir le PDF.'}}};
})();