(()=>{
'use strict';
function ensureQuickAccessLinks(){
  const actions=document.querySelector('#app .main > .top > .actions');
  if(!actions||actions.querySelector('[data-quick-access="links"]'))return;
  const access=document.createElement('a');access.className='btn secondary';access.href='../../admin/acces.html';access.textContent='Accès & liens';access.dataset.quickAccess='links';
  const site=document.createElement('a');site.className='btn secondary';site.href='../';site.textContent='Site Collège';site.dataset.quickAccess='site';
  actions.prepend(access);actions.prepend(site);
}
ensureQuickAccessLinks();
function readyBadge(a){return a.qr_ready&&a.qr_png_url&&a.qr_pdf_url?'<span class="pill ok">QR / PDF prêts</span>':'<span class="pill off">Préparation requise</span>'}
window.apps=function(){
  const list=[...db.applications].sort((a,b)=>(a.active===b.active?String(a.name).localeCompare(String(b.name),'fr'):a.active?-1:1));
  $('content').innerHTML=`<div class="toolbar"><button class="btn primary" onclick="editSite('','')">Créer une application</button><span class="muted">${list.filter(a=>a.active).length} active(s) · ${list.length} au total</span></div><br>${list.map(a=>{const c=cat(a.category_id),url='https://edm28contact-wq.github.io/gestion-college-app/college/?id='+encodeURIComponent(a.public_id),count=db.application_products.filter(m=>m.application_id===a.id&&m.active).length;return `<div class="card"><div class="top"><div><b>${esc(a.name)}</b> ${statusPill(a.active)} ${a.active?readyBadge(a):''}<div class="muted">${esc(c?.name||'Sans catégorie')} · ${count} produit(s) · code ${esc(a.code)}${a.qr_generated_at?` · QR généré ${new Date(a.qr_generated_at).toLocaleString('fr-FR')}`:''}</div></div><div class="actions">${a.active?`<a class="btn primary compact" target="_blank" rel="noopener" href="${url}">Ouvrir</a><button class="btn success compact" onclick="openAppQr('${a.id}')">QR / PDF</button>`:''}<button class="btn secondary compact" onclick="editSite('${a.id}','${a.category_id||''}')">Configurer</button>${a.active?`<button class="btn danger compact" onclick="disableSite('${a.id}')">Désactiver</button>`:''}</div></div></div>`}).join('')||'<div class="card">Aucune application.</div>'}<div id="pageStatus" class="status"></div>`;
};
function app(id){return db?.applications?.find(a=>String(a.id)===String(id))}
function assetModal(a){const publicUrl='https://edm28contact-wq.github.io/gestion-college-app/college/?id='+encodeURIComponent(a.public_id);return `<div class="modal"><div class="box" style="width:min(720px,100%);text-align:center"><div class="top" style="text-align:left"><div><h2 style="margin:0">${esc(a.name||a.code||'Application')}</h2><div class="muted">Fichiers déjà générés et stockés</div></div><button class="btn secondary" onclick="closeModal()">Fermer</button></div>${a.qr_png_url?`<div style="padding:18px 0"><img src="${esc(a.qr_png_url)}" alt="QR code ${esc(a.name||'application')}" style="width:min(360px,85vw);height:auto;border:12px solid #fff;box-shadow:0 0 0 1px #dfe4e8;border-radius:8px"></div>`:'<div class="card warn" style="margin-top:16px">Le QR code n’est pas encore prêt.</div>'}<div style="font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;word-break:break-all;background:#f6f8fa;padding:10px;border-radius:8px;text-align:left">${esc(publicUrl)}</div><div class="actions" style="justify-content:center;margin-top:14px">${a.qr_pdf_url?`<a class="btn primary" target="_blank" rel="noopener" href="${esc(a.qr_pdf_url)}">Ouvrir / imprimer le PDF</a><a class="btn success" download="qr-${esc(a.code||'application')}.pdf" href="${esc(a.qr_pdf_url)}">Télécharger le PDF</a>`:''}<button class="btn secondary" onclick="regenerateAppAssets('${a.id}')">Régénérer</button></div><div id="qrAdminStatus" class="status"></div></div></div>`}
window.openAppQr=id=>{const a=app(id);if(!a)return;$('modal').innerHTML=assetModal(a)};
window.regenerateAppAssets=async id=>{const s=$('qrAdminStatus');try{if(s){s.className='status';s.textContent='Régénération du QR code et du PDF…'}const r=await call(SITE,'regenerate-assets','POST',{id});const a=app(id);if(a){a.qr_ready=!!r.qr_ready;a.qr_png_url=r.qr_png_url||a.qr_png_url;a.qr_pdf_url=r.qr_pdf_url||a.qr_pdf_url;a.qr_generated_at=r.qr_generated_at||a.qr_generated_at}$('modal').innerHTML=assetModal(a);const s2=$('qrAdminStatus');if(s2){s2.className='status ok';s2.textContent='QR code et PDF régénérés.'}}catch(e){if(s){s.className='status err';s.textContent=frError(e.message)}}};
})();